### ISSUE TITLE
Missing dashboards possibly

### ISSUE THREAD

**Issue by dshipuk** [BloomTech-Labs/coder-heroes-fe#307]
I noticed we have a superadmin role and an admin role.

I know we're working on an admin dashboard, but I'm not sure if we would use the same dashboard for a superadmin.

If we do need a separate dashboard for a superadmin we're first going to need a ux design before it's worked on in the code base.

I also noticed we don't have any dashboard for a child.

What we already have: Instructor, Parent, Admin(WIP)

What I think we need: Child, SuperAdmin?

**Comment by paulstgermain** [comment]
Child dashboards are accessed through the Parent dashboard - they don't log in on their own, as laws regarding personal accounts for children are very strict. I would actually recommend crafting 1 Admin dashboard, and dynamically rendering specific options depending on Admin level.
