### ISSUE TITLE
Reusable Search Bar Component

### ISSUE THREAD

**Issue by reneetro** [BloomTech-Labs/coder-heroes-fe#322]
Create a reusable search bar component (using AntD) to be used across multiple pages to insure consistency and increase efficiency. Can search any page for text.

**Comment by paulstgermain** [comment]
I'd love to discuss this ticket more before approving - what pages/features do we need the search bar for? 🤔

**Comment by paulstgermain** [comment]
@reneetro ^ 😄

**Comment by reneetro** [comment]
Sorry I didn’t see this earlier (my inbox in a mess right now 🤫) @lisamdespain and @theecolya  and I were thinking that an admin might want the ability to search for instructors/courses on multiple pages (Admin View All Courses, View All Instructors, maybe on the dashboard?) Im not too familiar with search bars yet, but a parent/instructor might also need to search for courses so one main search bar component would save some time and make the page more consistent. Not sure if filter buttons are the way to go because of the size of the db now 🤷‍♀️

**Comment by jpivvt** [comment]
This is something we could consider for the future. In the app's earliest stage, we will have very few courses and instructors to have to sort/search for. We can drop something like this into the backlog until we are in a better position for more advanced features like this.
